version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"            # si tu solution .sln está en la raíz
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/auth-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/rooms-service"
    schedule:
      interval: "weekly"
