version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Unidad1_AsegurandoCodigoFuente"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Unidad1_AsegurandoCodigoFuente/auth-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Unidad1_AsegurandoCodigoFuente/rooms-service"
    schedule:
      interval: "weekly"
