version: '3.8'
services:
  rooms:
    build:
      context: ./rooms-service
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80

  frontend:
    image: nginx:stable
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
