version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - auth
      - rooms
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS=http://+:80

  rooms:
    build:
      context: ./rooms-service
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS=http://+:80

  frontend:
    image: nginx:stable
    expose:
      - "80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro