FROM nginx:stable
# Copia nginx.conf y el webapp usando rutas desde la raíz del repo (context = ../..)
COPY Unidad2_DespliegueSeguro/docker/nginx.conf /etc/nginx/nginx.conf
COPY Unidad2_DespliegueSeguro/webapp/ /usr/share/nginx/html/
EXPOSE 80
